content:
- name: faqakryesore
  label: Faqa Kryesore
  path: src/index.md
  type: file
  fields:
  - name: layout
    label: layout
    type: string 
    hidden: true
    default: layouts/index.njk
  - name: fusha
    label: Website title
    type: string